---
    name: Publish Python Images
    on:
      schedule:
        - cron: '0 2 * * *'
      push:
        paths:
          - 'Dockerfile'
        branches:
          - main
      workflow_dispatch:

    jobs:
      build:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            python_version: ["3.10", "3.11", "3.12", "3.13"]
            ubuntu_stream: ["stable", "rolling"]
            arch: ["amd64", "arm64"]
            include:
              - arch: amd64
                os: ubuntu-24.04
                platform: linux/amd64
              - arch: arm64
                os: ubuntu-24.04-arm
                platform: linux/arm64
        steps:
          - uses: actions/checkout@v4
          - uses: docker/setup-buildx-action@v3
          - name: Login to Github Registry
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}
          - name: Build and push ${{ matrix.arch }}
            uses: docker/build-push-action@v6
            with:
              context: .
              file: Dockerfile
              platforms: ${{ matrix.platform }}
              build-args: |
                PYTHON_VERSION=${{ matrix.python_version }}
                UBUNTU_STREAM=${{ matrix.ubuntu_stream }}
              cache-from: type=gha
              cache-to: type=gha
              pull: true
              push: true
              tags: ghcr.io/${{ github.repository }}:${{ matrix.python_version }}-${{ matrix.ubuntu_stream }}-${{ matrix.arch }}
              provenance: false
              sbom: false
      
      release-image:
        needs: build
        runs-on: ubuntu-24.04
        strategy:
          matrix:
            python_version: ["3.10", "3.11", "3.12", "3.13"]
            ubuntu_stream: ["stable", "rolling"]
        steps:
          - name: Login to Github Registry
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}
          - name: Push Multi-Arch Images
            run: |
              docker buildx imagetools create \
                -t ghcr.io/${{ github.repository }}:${{ matrix.python_version }}-${{ matrix.ubuntu_stream }} \
                ghcr.io/${{ github.repository }}:${{ matrix.python_version }}-${{ matrix.ubuntu_stream }}-amd64 \
                ghcr.io/${{ github.repository }}:${{ matrix.python_version }}-${{ matrix.ubuntu_stream }}-arm64

              # Tag 'stable' stream as default (no stream suffix)
              if [ "${{ matrix.ubuntu_stream }}" = "stable" ]; then
                docker buildx imagetools create \
                  -t ghcr.io/${{ github.repository }}:${{ matrix.python_version }} \
                  ghcr.io/${{ github.repository }}:${{ matrix.python_version }}-stable-amd64 \
                  ghcr.io/${{ github.repository }}:${{ matrix.python_version }}-stable-arm64
              fi